repos:
- repo: local
  hooks:
  - id: terraform-fmt
    name: Terraform fmt
    entry: terraform fmt -check -diff
    language: system
    exclude: '^\.history/.*'
    files: \.tf$

  - id: terraform-validate
    name: Terraform validate
    entry: terraform validate
    language: system
    files: \.tf$
    pass_filenames: false
    stages: [commit]
